androguard/androguard

androguard/gui/mainwindow.py
Missed in commit 61ee7fd533182da67551ce3df2cd83802f65c013
=> Fix import in GUI

androguard/core/bytecodes/api_permissions.py
delete "\t\t\t" in "UPDATE_DEVICE_STATS\t\t\t"(in two place)
=> fix a format bug in api_perssions.py

androguard/core/bytecodes/apk.py
A backport of https://github.com/iBotPeaches/Apktool/commit/0d950f3 to androguard
=> Fixed #33: Androguard and android-21

androguard/core/analysis/sign.py
=> Update sign.py (fix bug of _get_strings_pa)

androguard/core/bytecodes/dvm.py
fix bug of data_off_obj & checksum
=> Update dvm.py (fix bug of data_off_obj & checksum)

androguard/core/androconf.py
/cc @subho007 @adesnos 
- addresses #99
=> Relative path

androguard/core/analysis/analysis.py
=> Correction of the bug #110

setup.py
Remove `androrisk.py`, `androxgmml.py`, `androapkinfo.py` from `setup.py`
=> Some scirpts no longer exist

elsim/elsim/elsign/libelsign/elsign.cc
=> Fixes #122

androguard/core/bytecodes/apk.py, tests/test_arsc.py
There was some code that I haven't covered with tests and hence it wasn't working. Fixed that.
=> [apk] ARSC: fix config management and cover with tests

.travis.yml, README.md, requirements.txt, setup.py
resolves #213 
beware: this changes the travis file too, to use python3.6
It might occur that at least 2 test cases will fail there...
=> change dependencies and clean documentation

androguard/core/analysis/analysis.py
=> implement show function for DVMBasicBlock

androguard/core/bytecodes/apk.py
FIx crash in a poorly tested code
=> [apk] ARSCParser.ResourceResolver: fix handling of complex resources.

androguard/core/bytecode.py, androguard/decompiler/dad/opcode_ins.py, androguard/decompiler/dad/writer.py
Some unicode and byte conversions where overseen because all exceptions where caught. This should fix the problems with not completly decompiled source.
=> fix some unicode bugs with the decompiler

androguard/core/bytecodes/apk.py
Anyone has a better idea how to resolve this issue with python2?
=> Resolve issue #237 by explictly checking for non integer values.

setup.py
Fix https://github.com/androguard/androguard/issues/239
=> Fix travis build

.travis.yml, requirements.txt, setup.py
Maybe this fixes the bugs, as I'm not able to reproduce it on my local machine...
=> Adding Python 3.5 as well, as the failing test looks like a specific problem to 3.6

androdd.py, androguard/core/androconf.py, androguard/core/bytecode.py
Try to fix #218 - not sure what the original issue is here, maybe @feicong can you check with your sample if it works now?
=> Fix unicode errors in androdd and related classes

androguard/core/bytecodes/apk.py, androguard/misc.py
=> implement getstate and setstate for APK to avoid pickling problems

androguard/core/data/data.py
This one resolves #234 
Maybe there is more to do here?
=> Remove dotbuff calls

androguard/core/bytecodes/apk.py
I tidied up the `get_file_types` function, as it was quite repetitive.
=> Rewrite APK magic file type guessing

.travis.yml, androguard/core/bytecodes/dvm.py, tests/test_rename.py
This commit should resolve issue #253 
@cdkorzen can you check if it does? I tried your code and created a test case, which works now fine!
=> Fix renaming methods

androguard/__init__.py, androguard/core/androconf.py, setup.py
This one fixes #274 and introduces a very nice an clean way to handle the version number in setup.py
=> define a consistent version variable

androguard/core/analysis/analysis.py
Add get_methods to ExternalClass, so method search will work
=> Fix get methods

androguard/core/bytecodes/apk.py, androguard/gui/HexViewMode.py, androguard/gui/binwindow.py
The "magic_file" field should be checked like the code snippet above
- Androguard Version: master
- Python Version: 2.7 (Anaconda32)
- OS: Windows 7 64bit
=> check magic file before using it

androguard/core/bytecodes/apk.py
Signed-off-by: Young-Ho Cha ganadist@gmail.com
=> apk: build locale code properly

tests/test_decompiler.py
=> More test cases for decompiler processing

androguard/core/bytecode.py, androguard/core/bytecodes/dvm.py, androguard/decompiler/dad/ast.py, tools/test_androguard_apk_collection.py
=> fix some issues regarding strings and newer changes

androguard/core/data/data.py
Hi,
This really solves #234 
Cheers,
Pierre
=> Remove dotbuff calls, resolves #234

androguard/core/analysis/analysis.py
fix issue [329](https://github.com/androguard/androguard/issues/329)
=> fix-getlength-error

androguard/core/bytecodes/dvm.py, setup.py
maybe rework the function later...
=> use generator as list again to access last element

README.md
See https://github.com/androguard/androguard/pull/345#issuecomment-345974617
=> Make a note that androguard works with PyPy 5.9.0

andromark.py, andrototal.py
andrototal - uses virustotal.com public api to scan/rescan, comment and print reports on apk/dex files
andromark - prints apk/dex file's signatures
=> andrototal.pt and andromark.py

.travis.yml, androguard/core/bytecodes/dvm.py, requirements.txt, test-requirements.txt, tests/test_analysis.py, tests/test_apk.py, tests/test_arsc.py, tests/test_axml.py, tests/test_decompiler.py, tests/test_decompilerjadx.py, tests/test_dex.py, tests/test_rename.py, tests/test_session.py, tests/test_types.py
=> codecoverage

androguard/misc.py, tests/test_apk.py
Filename or the the filename of the android application or a buffer which represents the application
=> Added switch for raw in AnalyzeAPK

androguard/core/bytecodes/apk.py, androguard/core/bytecodes/axml.py
See this blog post for reference: https://mikeknoop.com/lxml-xxe-exploit/
=> Security fix for XML external entities

androguard/core/bytecodes/dvm.py
When parsing dex files, there are plenty of warnings:
<pre>unknown string item @ 0x%x(%d)</pre>
This is caused during creation of MapItem (which are in turn created in MapList). If MapItems are parsed before the MapItem of type TYPE_STRING_DATA_ITEM is processed, the calls to get_raw_string fail with the above log message.
In the PR I delayed the parsing of MapItem so TYPE_STRING_DATA_ITEM can be processed first.
=> Parse TYPE_STRING_DATA_ITEM first

androguard/core/bytecodes/dvm.py
Caching these 2 types makes loading of dex files much faster.
=> Cache TYPE_TYPE_LIST and TYPE_CLASS_DATA_ITEM

.travis.yml, androguard/core/analysis/analysis.py, androguard/core/bytecode.py, androguard/core/bytecodes/dvm.py, setup.py, tests/test_analysis.py
starting to do some reformatting on the Analysis module.
This is heavily work in progress! So do not merge...
See #221 for more information
=> [WIP] Tainted

androaxml.py, androguard/core/bytecodes/apk.py
i thx re.match is better than re.search and then filter is good for this situation
=> get filename of dex in apk and bug fix

androguard/core/bytecodes/dvm.py, androguard/core/bytecodes/mutf8.py, tests/test_strings.py
Better: what would be the string?
See #392
=> [WIP] on unicode decode error, escape surrogates

androguard/core/bytecode.py, androguard/core/bytecodes/apk.py, androguard/core/bytecodes/axml.py
On implementing FLAG_WEAK for the ARSC Parser. See #401
=> Fix unknownflag arsc

setup.py
=> enhance the setup.py

androguard/core/bytecodes/mutf8.py
=> fix for narrow python build

androguard/core/analysis/analysis.py, androguard/core/bytecodes/apk.py, androguard/misc.py, androguard/session.py, docs/intro/gettingstarted.rst, docs/intro/index.rst, docs/intro/sessions.rst
=> change behaviour of AnalyseAPK

androguard/core/bytecodes/apk.py
Fixing https://github.com/androguard/androguard/issues/512
=> Showing subject info for app certificates

androguard/misc.py, androguard/session.py
Some methods had the wrong return value documented.
This resolves #581
=> Fix documentation of methods

androguard/core/bytecodes/axml/__init__.py, docs/intro/installation.rst, setup.py, tests/test_axml.py
the regex would not work on python 2 as it displays surrogate pairs as two 16bit units.
=> fixing py2 regex

.travis.yml, androguard/core/analysis/auto.py, androguard/core/bytecode.py, androguard/core/bytecodes/apk.py, androguard/core/bytecodes/dvm.py, androguard/gui/helpers.py, androguard/gui/xrefwindow.py, androguard/session.py, tests/test_analysis.py, tests/test_apk.py, tests/test_session.py
resolves #527 
resolves #435 
resolves #548 
resolves #618 
resolves #458 
and maybe more for 3.3.5
=> [WIP] bugsquashing

androguard/core/bytecodes/apk.py, tests/test_arsc.py
@reox can you please check this PR? I have fixed few bugs as well. Abstracted the xml parsing, removed `get_element` and `get_elements` and used a better approach.
Let me know if you have any suggestion
=> Fix xmlparser abstraction

androguard/core/bytecodes/dvm.py, androguard/decompiler/decompiler.py, androguard/gui/Banners.py, androguard/gui/BinViewMode.py, androguard/gui/DataModel.py, androguard/gui/DisasmViewMode.py, androguard/gui/HexViewMode.py, androguard/gui/SourceViewMode.py, androguard/gui/binwindow.py, androguard/gui/fileloading.py, androguard/gui/mainwindow.py, androguard/gui/sourcewindow.py, androguard/gui/xrefwindow.py, androguard/session.py
resolves #635 
resolves #620 
resolves #619
=> Fix a few things in the gui

androguard/core/bytecodes/dvm.py
really need to go through all the classes and clean up unused code...
=> adding some comments and optiziming code readability

androguard/core/api_specific_resources/__init__.py, androguard/core/api_specific_resources/aosp_permissions/permissions_10.json, androguard/core/api_specific_resources/aosp_permissions/permissions_13.json, androguard/core/api_specific_resources/aosp_permissions/permissions_14.json, androguard/core/api_specific_resources/aosp_permissions/permissions_15.json, androguard/core/api_specific_resources/aosp_permissions/permissions_17.json, androguard/core/api_specific_resources/aosp_permissions/permissions_18.json, androguard/core/api_specific_resources/aosp_permissions/permissions_19.json, androguard/core/api_specific_resources/aosp_permissions/permissions_21.json, androguard/core/api_specific_resources/aosp_permissions/permissions_22.json, androguard/core/api_specific_resources/aosp_permissions/permissions_23.json, androguard/core/api_specific_resources/aosp_permissions/permissions_24.json, androguard/core/api_specific_resources/aosp_permissions/permissions_26.json, androguard/core/api_specific_resources/aosp_permissions/permissions_27.json, androguard/core/api_specific_resources/aosp_permissions/permissions_28.json, androguard/core/api_specific_resources/aosp_permissions/permissions_4.json, androguard/core/api_specific_resources/aosp_permissions/permissions_5.json, androguard/core/api_specific_resources/aosp_permissions/permissions_6.json, androguard/core/api_specific_resources/aosp_permissions/permissions_7.json, androguard/core/api_specific_resources/aosp_permissions/permissions_8.json, androguard/core/api_specific_resources/aosp_permissions/permissions_9.json, androguard/core/bytecodes/apk.py, tests/test_apk.py
=> adding new permission lists, resolving #529

.travis.yml
=> testing with jadx 0.9.0

androguard/cli/entry_points.py, androguard/core/analysis/analysis.py
=> Add more properties for CG

androguard/core/bytecodes/dvm.py, androguard/core/bytecodes/dvm_types.py, tests/test_loadorder.py, tests/test_rename.py
I used the work referenced in #376 in order to remove reloads.
Let me know if you find something strange / wrong.
Resolves : #388
=> Remove reloading of map items

androguard/core/bytecode.py, androguard/core/bytecodes/dvm.py, androguard/core/bytecodes/dvm_types.py, androguard/gui/DisasmViewMode.py
The html building code needs some further refactoring for sure.
This should also reduce the number of failures with pydot.
=> Refactor parts of the CFG creation

docs/intro/instructions.rst
great example according to reox ‘s suggestion
=> add an example for finding specific disassembled instructions

docs/intro/sessions.rst
Change "hundrets" --> "hundreds"
=> Fix typo in Sessions

androguard/core/bytecodes/apk.py
This CL lazily loads the APK into memory instead of reading it upfront.
=> Significantly improve basic APK parsing performance on large files

androguard/core/analysis/analysis.py
Hi @reox,
I would like to know whether it is helpful to provide this `get_android_api_usage` function. In many malware analysis cases, we hope to be able to get all Android APIs usage, and some APIs may not require permission to use, so providing this method allows users to get all Android APIs.
For example:
```python
a, d, dx = AnalyzeAPK("14d9f1a92dd984d6040cc41ed06e273e.apk")        
for meth_analysis in dx.get_android_api_usage():                                                                   
print(meth_analysis.full_name)        
```
The output could be:
```
Ljava/lang/Object; <init> ()V                                                                                      
Ljava/lang/Object; equals (Ljava/lang/Object;)Z …
```
=> add get_android_api_usage method in Analysis class

androguard/misc.py
fix AttributeError: 'bytes' object has no attribute 'DEX'
=> fix AttributeError

androguard/core/axml/__init__.py
Related with https://github.com/androguard/androguard/issues/953
- Restored prior to commit https://github.com/androguard/androguard/commit/8427b0896ce97541ce568ec718a1b90e03a4eab5
=> Restored prior to commit 8427b08

androguard/core/apk/__init__.py
based on the integration with apkInspector https://github.com/androguard/androguard/pull/956, I adjusted the get_apkid and the creation of the new zip.
=> fix get_apkid and new_zip

androguard/core/dex/__init__.py
=> fix 4-byte aligned padding

androguard/core/axml/__init__.py
based on receiving the apk this is a more appropriate fix
https://github.com/androguard/androguard/issues/1006
=> supplementary for 1006

androguard/core/apk/__init__.py
main_activities is of type set, but index access was used, resulting in TypeError. Use the sorted() method to convert it to a list type, and then access it through subscripts.
=> fix 'set' object is not subscriptable error.

androguard/core/apk/__init__.py, tests/test_apk.py
[4c7d2912ba24e4bf1dab1175ee435f85ec223ac86967fc61a3dacbd1a97ee329](https://www.virustotal.com/gui/file/4c7d2912ba24e4bf1dab1175ee435f85ec223ac86967fc61a3dacbd1a97ee329/details)
Permission `android.permission.READ_EXTERNAL_STORAGE` not checked out
=> Read tags with android namespace

README.md, androguard/core/analysis/analysis.py, androguard/core/apk/__init__.py, androguard/core/axml/__init__.py, androguard/session.py, androguard/ui/__init__.py, androguard/util.py, tests/test_analysis.py, tests/test_apk.py, tests/test_dex.py
hi, there
i some fix some typo on code and docs.
=> Fix some typo

androguard/core/axml/__init__.py, androguard/core/dex/__init__.py
https://github.com/androguard/androguard/issues/1067
https://github.com/androguard/androguard/issues/1069
=> fix issues 1067 and 1069

androguard/core/apk/__init__.py, androguard/core/axml/__init__.py
https://github.com/androguard/androguard/issues/1073
=> Empty element name

androguard/core/axml/__init__.py
https://android.googlesource.com/platform/frameworks/base/+/master/libs/androidfw/ResourceTypes.cpp#827
https://github.com/androguard/androguard/issues/1119
=> warn on non-null terminated string

androguard/core/axml/__init__.py
https://github.com/androguard/androguard/issues/1133
=> relaxing header chunks
