androrisk.py
use zipmodule=2 in androrisk.py,fix the error:
File "/usr/lib/python2.7/zipfile.py", line 373, in _decodeExtra
tp, ln = unpack('<HH', extra[:4])
struct.error: unpack requires a string argument of length 4
=> fix a zipmodule wrong in androrisk.py

androguard/core/bytecodes/dvm.py
array-length vA, vB
A: destination register (4 bits)
B: array reference-bearing register (4 bits)
Store in the given destination register the length of the indicated array, in entries
=> Array-length has no type reference, see the Dalvik document.

androguard/core/bytecodes/dvm.py
- 1. result = unpack( '=b', buff.read(1) )[0]
if result <= 0x7f:
...
Wont work with multi-bytes leb128, as the "result" will be read
as signed value and in multi-bytes, the MSB of all but the last
byte are all set to 1.
Therefore the "result", which is read as the first byte of a
leb128 will always be negative, hence this condition test will
always be true. Which means, it really just reads one byte and
stops there for every signed leb128.
- 2. result = (result << 18) >> 18
...
This , which I believe is to extend the sign bit, won't work with
negative number neither, as after bit operator, result could become
positive from negative.
Tese case like this:
t = -624485
assert (t == dvm.readsleb128_1(bytecode.BuffHandle(dvm.writesleb128(t))))
Would show what happens.
=> The original readsleb128 has two major bugs.

androguard/core/bytecodes/dvm.py
1. StringDataItem + "\x00"
2. Fix CodeItem offset
PS: bugs of DebugInfoItem still in process
=> Fix bugs of dex.save()

androguard/core/androconf.py, androguard/core/bytecodes/apk.py
The previous version of 'is_android_raw' is not able to detect some *.apk files in which the string 'PK' is not in the first block of 7 bytes and it's position is variable.
So, to correctly detect all *.apk files we need also to check some immutable resources which are absolutely present in their packages, such as 'AndroidManifest.xml' and 'META-INF/MANIFEST.MF'.
=> Fix for is_android_raw in detecting *.apk files

androguard/core/bytecodes/apk.py
Magic.from_buffer returns None when it cannot find a file type.
This is never checked and causes an Exception when None is returned
because the return value is  given as an argument to
the APK._path_magic method.
modified:   androguard/core/bytecodes/apk.py
=> Bug correction related to file types.

androguard/core/bytecodes/dvm.py
For the fill array instruction, the play load length is defined:
Note: The total number of code units for an instance of this table is (size * element_width + 1) / 2 + 4.
What it really means that is to round size * element_width in size of two bytes.
For example:
Suppose the size*element_width = 1, then  (1+1)/2 + 4 = 5  (2 byte code units).
And if size*element_width = 2, then (2+1)/2 + 4 = 5 ( 1.5 is truncated into 1 when performing integer division).
Therefore, it round the odd size*element_width and keeps the even size*element_width.
The original implementation actually add one byte to the length of payload, which is utterly wrong.
=> Fix bug: wrong array length calculation in FillArray instruction.

androguard/core/bytecodes/apk.py
APKs can be signed using RSA, DSA and EC keys. This
change allows you to be able to see the EC key suffix
when searching an APK. I've also added new methods to
return a list of _all_ signatures found opposed to just
the first.
The older methods are still available for backwards
compatability. They have been refactored to select
the first of the list, which is how the previous
functionality would have worked.
=> Fix APK signature methods.

androguard/core/bytecodes/apk.py
This PR allows for filemagic support in addition to python-magic. This is needed for environments already making use of filemagic, because python-magic and filemagic cannot be used in the same environment or virtual environment.
This PR also addresses the issue raised in #124.
=> Add Support For Filemagic

androguard/core/bytecodes/apk.py
`com.expedia.bookings` has it's main activity defined only in an activity alias:
``` xml
<activity-alias android:name="com.expedia.bookings.activity.SearchActivity" android:targetActivity="com.expedia.bookings.activity.RouterActivity">
<intent-filter>
<action android:name="android.intent.action.MAIN" />
<category android:name="android.intent.category.DEFAULT" />
<category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
</activity-alias>
```
When attempting to retrieve the main activity with Androguard:
```
In [7]: from androguard.core.bytecodes.apk import APK
In [8]: a = APK("/Users/fuzion24/Downloads/com.expedia.bookings.apk")
In [9]: a.get_main_activity()
In [10]:
```
After the patch:
```
In [5]: from androguard.core.bytecodes.apk import APK
In [6]:  a = …
```
=> Support finding main activity via activity aliases

androguard/core/bytecodes/apk.py
I found some malicious apps register several main activities as below:
there are 2 main activities but one of them has android:enabled="false"
that will lead to get wrong main activity by
androguard(a.get_main_activity method);
=> fix bug on getting main activity

androguard/core/bytecodes/apk.py
It occoured to me, that the ARSCParser Output could not be parsed by lxml or xml.etree because &, < and > where not escaped. This patch should fix that.
I think it is not necesssary to escape Bool, Color, Integer and Dim as well?
=> adding xml escape to strings in ARSC to produce valid xml

androguard/core/bytecodes/apk.py
This fixes a bug (error calling function on None type) caused when a
system attribute is encountered that is not in the list of system
attributes in android.core.resources.public. This was encountered
when an AndroidManifest.xml file contained a tag with a newer system
attribute (e.g. <intent-filter android:autoVerify="true">) The
"autoVerify" string is not found in android.core.resources.public
so None is returned. This causes the AXMLPrinter to print XML that
is invalid, eventually causing minidom to fail to parse it. Then
when an analyzer tries to lookup a value in the AndroidManifest the
lookup fails because the xml is None and analysis can't proceed.
By returning a default value when a system attribute lookup fails, we
future proof against other unknown SYSTEM_ATTRIBUTES
=> Added 'android:UNKNOWN_SYSTEM_ATTRIBUTE' for unfound attributes

androguard/core/bytecodes/apk.py
The only APK so far that can be used to reproduce a crash which is fixed by this PR can be downloaded [from google play](https://play.google.com/store/apps/details?id=com.alibaba.intl.android.apps.poseidon)
I am not sure if it is OK to include 3rd party APK or even it's resources file into the test suite, so I didn't do that.
On the other hand, I am also not aware of an easy way to generate an arsc file with the non-standard header sizes (which is the reason for the crash).
=> Arsc corrections

androguard/core/bytecodes/apk.py
some apps would not have an app name set.
One example is APK with MD5 9F4186D5E32A30D79FBE76861FDC3CDE
=> resolve missing app name crash

androguard/decompiler/dad/writer.py
Modify the display of array data to consider the element size.  Previously,
anything other than an integer (4 bytes) would cause DAD's writer
to error out when visiting the fill-array payload.
=> Update how array data is printed

androguard/core/bytecodes/apk.py
The get_files_types method is the most CPU intensive part of parsing an APK and on some bigger APKs can take minutes depending on your machine.  This param lets you optionally skip it.
=> Add skip files parse param

androguard/core/bytecodes/apk.py
Using str() causes UnicodeEncodeError in get_elements(), hence in get_activities(), get_services(), etc.
=> .encode('utf-8') instead of str()

androguard/decompiler/dad/dataflow.py, androguard/decompiler/dad/decompile.py
fixes for crashes if tmp variables are created but later not found
=> try to fix decompiler crashes due to tmp variables

androguard/core/bytecodes/dvm.py
NNNN is the last register filled, thus it should be in the output as
well.
=> resolve #97

androguard/core/bytecodes/apk.py, tests/test_apk.py
#354 resolved with changes on line 538 of apk.py. Tests added in test_apk.py to test that a string type is returned for get_activities(), which currently returns a byte class.
#355 resolved with moving the new_files check outside of the deleted_files check. No tests for this, and I haven't added any in this PR.
=> fixing #354 with unit tests and #355

androguard/core/analysis/analysis.py, androguard/misc.py, androguard/session.py, tests/test_session.py
Following are the changes:
1. Instead of using the `last_vm` get the `vm` dynamically via ClassManager
2. do the analysis on all the `vm` present in `self.vms`
3. Refactor `session.py` to support multidex analysis
@reox @adesnos can you please review the changes ? I'll write testcases in different PR
fixes #373 #359
=> Allow multidex analysis

androguard/core/bytecodes/apk.py, androguard/core/bytecodes/axml.py
As discussed in #377 the following are implemented:
1. Remove SAX to DOM parser
2. Make all the methods in `apk.py` compatible with `lxml`'s etree parser
@reox please review
fixes #377
=> Use lxml etree instead of converting from SAX to DOM

androguard/core/androconf.py
In `Python3` you can't call `decode()` on a `str` object, so this workaround should work with both `Python2` and `Python3`.
=> Make ASCII detection compatible with Python3

androguard/core/bytecodes/apk.py, androguard/util.py, setup.py, tests/test_apk.py
so many bugs in pyasn1. asn1crypto is more easy in use, and no need cryptography any more.
=>   switch pyasn1 to asn1crypto

androguard/core/bytecodes/dvm.py
I was tested this apk [snaptube](https://apkpure.com/snaptube/com.snaptube.premium).
It took error this `  File "/home/x/androguard/core/bytecodes/dvm.py", line 7246, in get_proto
return [proto.get_parameters_off_value(),
File "/home/x/androguard/core/bytecodes/dvm.py", line 2096, in get_parameters_off_value
self.parameters_off_value = '({})'.format(' '.join(params))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u15ee' in position 3: ordinal not in range(128)`
so i add keyword u(unicode) to format string and it's working good.
=> python2 didn't support unicode with format

androguard/core/analysis/analysis.py
If an apk contains multiple dex for instance `classes1.dex` and `classes2.dex`. If method `A`  in `classes1.dex` invokes method `B` which is in `classes2.dex`, method `B` will only be searched in `classes1.dex`. So we will get nothing because method `B` is in `classes2.dex`. Instead we should search all classesN.dex for method `B`.
=> fix bug for xref from multi dex

androguard/core/bytecodes/apk.py
It is raised from `APK.get_elements()` and `APK.get_main_activity()` when parsing of `AndroidManifest.xml` failed in `APK._apk_analysis()` - `self.xml["AndroidManifest.xml"] is set to `None`.
Same fix is already implemented in `APK.get_element()`.
=> Fix `NoneType` obj has no attribute `findall`.

androguard/core/bytecodes/apk.py
Nothing has changed for `APK.get_main_activity()`.
`get_main_activities()` uses previous implementation of the `APK.get_main_activity()` but returns all the found activities.
=> Add APK.get_main_activities() method

androguard/core/bytecodes/apk.py
Description of the method states that it returns list of strings, so `None`
should not be there. According to the [docs](https://developer.android.com/guide/topics/manifest/activity-element#nm), name must be specified, so warning is logged in such a case.
Sample hash: 1A26B4F5C1DAE78F62B064014A9250ED79292CBFFCD7E07A1A88B64CAAA317BE
=> Do not return `None` in list of main-activities.

androguard/cli/entry_points.py, androguard/core/bytecodes/apk.py
This first tries to do quick binary XML parsing to just get the values that are needed.  It will fallback to full androguard parsing, which is slow, if it can't find the versionName value or versionName is set to a Android String Resource (e.g. an integer hex value that starts with @).
@reox this is what we hacked together the other night
=> create 'androguard apkid' command for quite APK identification

androguard/core/bytecodes/apk.py
This is a fix for issue #559. This fixes a `KeyError` exception in `get_details_permissions`, `get_requested_aosp_permissions` and `get_requested_aosp_permissions_details`.
=> Fix KeyError in methods to get permissions

androguard/cli/main.py, androguard/core/bytecodes/apk.py
Hi,
I've implemented the APK signature scheme v3 which was missing from androguard. I relied on the following sources for the implementation :
* https://source.android.com/security/apksigning/v3 : official documentation about APK V3 signing
* https://github.com/avast/apkverifier/blob/master/signingblock/schemev3.go : Go implementation of the APK V3 signing parser.
This is a pretty new scheme, so not many APK has them (it is backwards compatible with V2) but you can test it with Google Play's APK. I also took some liberty to refactor the internal code since the parsing is extremely similar between V2 and V3.
Anyway if you have remarks or questions, feel free to ask.
Cheers
=> Add support for APK v3 signing block

androguard/core/bytecodes/axml.py
Fix unicode `language` and `region` not properly utf-8-encoded.
=> Closes #582: Fix language and region utf-8 encoding

androguard/cli/entry_points.py, androguard/core/bytecodes/axml/__init__.py, tests/test_arsc.py, tests/test_entry_points.py
```
$ androguard arsc  examples/tests/a2dp.Vol_137.apk --id 7F070058
@7f070058 resolves to '@a2dp.Vol:string/accessDescription'
<default> = 'Used to read notifications while connected to a device using A2DP Volume'
da = 'Bruges til at læse notifikationer der er forbundet til en enhed der bruger A2DP Volume'
ja = 'A2DP Volumeを使用しているデバイス接続中'
de = 'Wird verwendet, um Benachrichtigungen vorzulesen, wenn ein Gerät mit A2DP Volume verbunden ist'
el = 'Για χρήση ανάγνωσης ειδοποιήσεων ενώ είστε συνδεδεμένος σε συσκευή κάνοντας χρήση ήχου A2DP'
fr = 'Utilisé pour lire les notification lorsque connecté à un appareil utilisant A2DP Volume'
ru = 'Исп-ся для чтения уведомлений при соединении с уст-вом через A2DP Volume'
```
=> resolve IDs directly from cmdline

setup.py
026d42777291b893238c5d63c5200dda803e123b seems to want to undo some previous
changes, but it also removed androauto.py from setup.py.
=> androauto.py got mistakenly removed from setup.py, readd

androguard/core/bytecodes/axml/__init__.py
In order to not break existing tools, some functions were re-added.
Note that still some functions are renamed or even removed due to
refactoring and reorganization of the parser.
As the method of resolving namespaces has changed, some methods do
not make any sense. Please check your projects!
Detailed changes between 3.2.1 and 3.3.0:
StringBlock: Made some functions private, as they are not used from
the outside.
Renamed functions:
* decode8(self, offset) --> _decode8
* decode16(self, offset) --> _decode16
* decode_bytes(self, data, encoding, str_len) --> _decode_bytes (and static)
* decodeLength(self, offset, sizeof_char) --> _decode_length
AXMLParser: renamed some functions, also removed many namespace
parsing functions.
Renamed functions:
* reset(self) --> _reset
* doNext(self) --> …
=> Re-adding certain functions in the AXMLParser

androguard/core/bytecodes/apk.py, docs/intro/installation.rst, setup.py
This removes all magic implementation except the one of
python-magic.
This resolves two issues:
* resolves #439
* resolves #292
Note that the magic implementation for your operating system might
have issues. Please read the installation instructions of
python-magic: https://github.com/ahupp/python-magic/#installation
=> Remove other magic implementations

androguard/core/analysis/analysis.py, androguard/core/bytecodes/apk.py, androguard/core/bytecodes/axml/__init__.py, androguard/core/bytecodes/dvm.py
@subho007 sorry, I told you total BS in the last pull request... The `@DeprecationWarning` decorator is totally wrong and if you call the method you will just get an error. I'm not sure what I was thinking, but apparently I added that two years ago *shame on me*
So the correct method would be like this:
```
def deprecated_method()
"""
.. deprecated:: 1.2.3
use :meth:`other_method` instead. This method is likely to be removed in a later release.
"""
warning.warn("this method is deprecated!", DeprecationWarning)
```
I fixed this now everywhere I found it.
=> redo deprecation

README.md
Deckard uses Androguard to perform static analysis an Xposed modules. It attempts to extract which hooks are placed by the module.
Thanks for your work on Androguard!
=> Add Deckard to list of projects using Androguard

androguard/core/analysis/analysis.py, tests/test_analysis.py
This should:
* resolve #222
The naming has changed and also the returned values are different now!
Note that these methods might not catch all occurences of API usage
=> Re-implement permission based lookup of API methods

androguard/decompiler/dad/dast.py
A class may have more than one constructor. They have different
signatures. Ast's are pure strings and numbers. Without knowing the
signatures, a parser cannot tell precisely which constructor it is
handling.
=> Add 'triple' in an ast node for 'ClassInstanceCreation'.

androguard/core/analysis/analysis.py, androguard/core/bytecodes/dvm.py
It looks like that some specifications were not fulfilled
like aligned code.
This should work now, and if not there should be a warning.
=> Work around basic block creation for switch opcodes

androguard/core/bytecode.py, androguard/core/bytecodes/dvm.py, androguard/core/bytecodes/mutf8.py, tests/test_strings.py
I did some changes regarding the mutf8 package. I've merged `patch_string` and `decode` in one function and it seems to be faster.
**Single test with `patch_string(decode(b))` :**
```
Runtime : 30.26204100s
Name               | TotTime  |  Calls   | Source
patch_string                     | 7.212343 |   539456 | mutf8.py:97    
__next__                         | 4.871884 | 16732390 | mutf8.py:81    
decode                           | 3.503724 |   539456 | mutf8.py:25    
chr                              | 2.161444 | 16192935 | mutf8.py:6     
read                             | 1.811831 |  5206598 | bytecode.py:797   
<built-in method builtins.ord>   | 1.305763 | 37593719 |
read_null_terminated_string      | 1.109645 |   102793 | dvm.py:106   
<built-in method builtins.chr>   | 0.933014 | …
```
=> [RDY] Improving DEX parsing time

androguard/core/bytecodes/dvm.py, androguard/misc.py
resolve #703 
adding correct alignment for all items in the map
=> Fixing alignment when reading map

androguard/core/bytecodes/apk.py, setup.py
The correct exception is actually MagicException and not MagicError,
this was probably a relict of the old days.
Also removed support for python3.4, as other libraries we use do not
support it either.
resolves #726
=> Fix magic: Wrong exception caught

docs/tools/androdd.rst
Just encounter the problem of "dot" not found while using the feature of the call function graph. It could be resolved by telling the users to install the necessary packages. Running on Ubuntu 16.04 tests well.
=> remind user to install necessary packages.

androguard/misc.py, tests/test_misc.py
=> make filename length hard limit

androguard/core/bytecodes/apk.py
Getting a app_icon fails with:
errorinvalid literal for int() with base 16: 'android:01080411'
Example apk: bbc0b4a181171c1180d9f18763e9b0e91c929fa37cadae445abe0f4d4ac673d6
=> android:<id> fails getting app_icon id.

README.md
Thank you very much for each androguard maintainer, we create the quark-engine based on androguard,  this is an Obfuscation-Neglect Android Malware Scoring System to against android malware.
=> add Quark-Engine into Projects using Androguard

androguard/core/bytecodes/apk.py
Fix depreaction warning due to invalid escape sequences in Python 3.7.
=> fixs docstring in issue #796 by pyupgrade

androguard/gui/helpers.py
The original line: 
`self.class_components` = `self.cls.name.strip('L').strip(';').split('/')`
give the following error during the open phase of several apk files:
**TypeError:`** a bytes-like object is required, not **`'str'**
The problem can be easily solved casting explicitly the cls.name to string before manipulate it.
=> Add string casting to the cls.name

.travis.yml
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3
=> Added Power Support for ppc64le

androguard/core/bytecodes/dvm.py
This should return self.method_idx, not a function itself
=> Fix wrong return value of get_method_idx function

androguard/cli/main.py
The getting started guide does not work as expected without the import of AnalyzeAPK (see https://github.com/androguard/androguard/blob/master/docs/intro/gettingstarted.rst)
This commit fixes the interactive shell to be in line with the documentation.
=> synchronized behaviour with documentation

androguard/session.py
androguard gives me a confusing log output  when I tried to load a session.
```
{} already exists, overwriting!
```
Looking around `session.py` I found the weird log in line 46. , maybe it's better to print a more detailed log.
=> fix confusing log in session.py

setup.py
`pip install -e ".[tests]"` should install everything required for the
tests to run and pass.
Currently `tests/test_apk.py::testMagic` fails because the magic package
does not get installed.
=> Install magic when installing test dependencies.

androguard/core/axml/__init__.py
It may fix some issue with packed or obfuscated AndroidManifest.xml example, https://www.virustotal.com/gui/file/64275082cdec19c4e9d74efb9dfcaba133d1d2312e3670ad976750c9a77752cb
=> Fix AXML parsing error with manipulated

androguard/core/analysis/analysis.py
Bug on extracting xrefs, check of class fails because comparison is done with a byte character, while the index 0 from a string is a string in python3. In case other python version want to be supported, a cast can be applied to byte or to string.
=> Error getting xrefs

tests/test_types.py
The deprecated aliases have been removed in python/cpython#28268
=> Use assertEqual instead of assertEquals for Python 3.11 compatibility.

androguard/misc.py
Currently the vm is not used by DecompilerDAD, however it may cause the following exception if the decompiler use vm in the future:
```
File "/androguard/decompiler/decompiler.py", line 650, in __init__
tf.write(vm.get_buff())
AttributeError: 'list' object has no attribute 'get_buff'
```
=> Fix parameter of decompiler

androguard/core/analysis/analysis.py
The `xreffrom` of a `StringAnalysis` object are stored in tuples with 3 members (class, method and offset). However, the `__str__` method of the `StringAnalysis` class ignores the offset which casuse a `ValueError: too many values to unpack (expected 2)` exception. This PR fixes that.
Note that with this fix, the offset is not displayed in the output, but that could easily be added if that is preferable.
=> Fix ValueError when printing StringAnalysis object

androguard/core/axml/__init__.py
Fix the parsing of attributes that should based on ressourceids and not Stringblock to avoid some false information due to a corrupted AndroidManifest file
=> Fix the parsing of attributes on AXML file

androguard/core/apk/__init__.py, androguard/core/axml/__init__.py, requirements.txt
This PR utilizes [apkInspector](https://github.com/erev0s/apkInspector) to tackle common packer techniques targeting the zip structure of APK files. Additionally I have added the code, under the same principles the [axml](https://github.com/erev0s/apkInspector/blob/main/apkInspector/axml.py) module of apkInspector works, where it tackles static analysis evasion techniques employed on the AndroidManifest.
Testing apkInspector and androguard (as well other tools) against known malware which employs static analysis evasion techniques, can be found [here](https://erev0s.com/blog/unmasking-evasive-threats-with-apkinspector/)
Tests related to the reliability of the tool can be found [here](https://github.com/erev0s/apkInspector/tree/main/tests/top_apps). Additionally, the `test_axml.py` in …
=> employing apkInspector to tackle packers and common static evasion techniques

pyproject.toml
As mentioned in https://github.com/androguard/androguard/pull/957 there were still two things left before being possible to streamline the publishing to PyPI
- updating the name of the project in the pyproject.toml
- and setup the api token for PyPI
Initially i thought that whoever from the owners would setup the API token for the PyPI would also update the name, but since this seems to be taking some time, I am doing this PR to solely change the name of the project in the pyproject.toml so there are no issues if someone tries to install through pip directly from the repo.
=> update pyproject name

androguard/core/axml/__init__.py
Commit 03b841bf4175b0621c024a496fc064cbaeb81408 added a bug for some cases when getting the strings from the string pool from the resources.arcs. The bug was caused from line 163 changed in the current PR.
Besides that this snippet in lines 161-163 causing this bug for the resources.arcs it is also not necessary as the stringCount for the cases with packers is covered properly in lines 123-124 which I also updated to take into account the styleCount.
to test the difference you can use the `get_app_name()` in some apps
=> fix bug from 03b841bf4175b0621c024a496fc064cbaeb81408

androguard/core/apk/__init__.py
Unless we have better solution for multi part zip, it would be better ignoring and pretending it is single zip file. Found that some malwares use this trick to interrupt automated analysis like below sample. https://www.virustotal.com/gui/file/2b9eb34b2d86e9119ada81f2c641086225c420d3439a3ca22e2a903ce8c2c937
=> FIX? Ignore? multi disk ZIP error

androguard/core/apk/__init__.py
This pull request addresses a potential issue in the `_get_permission_maxsdk` method within the Androguard APK module. The current implementation could lead to a `TypeError` when `maxSdkVersion` is `None`. The proposed fix converts `maxSdkVersion` to a string in the `logger.warning` call, ensuring that the warning message is correctly logged without causing a TypeError.
- Modified the `_get_permission_maxsdk` method to handle the case where `maxSdkVersion` is `None`.
=> Fix maxSdkVersion warning in _get_permission_maxsdk method

androguard/core/apk/__init__.py
In some cases [self.get_files](https://github.com/androguard/androguard/blob/9e7f13a042356fe92ca0b23bd0a96caf77adfbc5/androguard/core/apk/__init__.py#L628) returns a file name such as classes.dex/sample.png. To avoid capturing such file names use strict regex `dexre = re.compile(r"^classes(\d*).dex$")`
Sample: 
[infected.zip](https://github.com/androguard/androguard/files/13810008/infected.zip) (password: infected)
Running:
```
from androguard.misc import AnalyzeAPK
from androguard.util import set_log
set_log("ERROR")
a,d,x = AnalyzeAPK("./63629c8dce75311526ef11e8a9f410ff51d8ae709df3de4aaf16887d8f056d17")
```
will result in 
```
Traceback (most recent call last):
File "/tmp/t.py", line 5, in <module>
a,d,x = AnalyzeAPK("./63629c8dce75311526ef11e8a9f410ff51d8ae709df3de4aaf16887d8f056d17") …
```
=> stricter regex to capture "official" classes.dex files

README.md, androguard/cli/cli.py, androguard/core/analysis/analysis.py, pyproject.toml, requirements.txt, tests/test_callgraph.py
- Readded several dependencies, such as networkx, matplotlib, pyyaml, and pyqt5 to generate and render callgraphs
- Readded previous get_call_graph() function and made a few fixes
- fixed some docstring inaccuracies with MethodAnalysis xref_from/to
- Can export callgraphs to gml, gexf, graphml, and net (pajek), **but not gpickel or yaml because there are embedded attributes that are not serializable in EncodedMethod objects (BufferedReader in EncodedMethod.buff)**. 
Tested with the following commands:
```bash
androguard --verbose cg --show --classname "Ltests/androguard/*" ~/projects/androguard/tests/data/APK/TestActivity.apk
```
```bash
androguard --verbose cg --show --methodname "Test*" ~/projects/androguard/tests/data/APK/TestActivity.apk
```
```bash
androguard --verbose cg --show …
```
=> Restore 'androguard cg' callgraph generation

androguard/core/axml/__init__.py
Androguard halts the parsing of resources if it encounters specific resource types (RES_TABLE_TYPE_SPEC_TYPE ) where the res1 and res0 fields are not both set to zero. In this PR I've implemented error handling measures to ensure continuation of the processing. 
This issue became apparent to me as I worked on parsing samples from the following apps:
- 1100f090f0c1d2d09940d6e9887da58fd15ae7d7eb3a064761f09d5ded189bf4 (com.airbnb.android, version  name 24.10) 
- 4e4396a7fd6d8b3d1bb77c6004d6845d035ce58bba0ce5a6a01962e6069cd480 (com.facebook.orca, version name 447.1.0.45.106)
=> Added error handling for ResParserError

androguard/core/axml/__init__.py
Fixing https://github.com/androguard/androguard/issues/1006
=> fix for 1006

androguard/core/analysis/analysis.py, androguard/core/dex/__init__.py, tests/test_analysis.py, tests/test_dex.py, tests/test_dexcodeparsing.py, tests/test_rename.py, tests/test_types.py
Refer to: https://github.com/androguard/androguard/issues/989#issuecomment-1925512272
- Add and wrap all fields in `FieldAnalysis`
- Add and wrap strings in `StringAnalysis`
- Update `test_analysis.py` unittest, because number of fields and strings returned are now increased
- Various refactoring for consistency, adding new convenience functions
=> Ensure all Fields and Strings get wrapped as FieldAnalysis and StringAnalysis respectivly when creating Analysis

androguard/__init__.py, androguard/core/axml/__init__.py, pyproject.toml
https://github.com/androguard/androguard/issues/1014
=> Reserved values res0/res1 error

androguard/core/axml/__init__.py
If manifest contains a space in `xmlns` attributes, APK can be installed without issue, but pyaxmlparser fails.
```
<manifest 
xmlns:android="http://schemas.android.com/apk/res/android" 
xmlns:tools="http://schemas.android.com/tools "
```
```
ValueError: Invalid namespace URI 'http://schemas.android.com/tools '
```
---
```
>>> etree.Element("manifest", nsmap={"tools": "http://schemas.android.com/tools"})
<Element manifest at 0x1226f1600>
>>> etree.Element("manifest", nsmap={"tools": "http://schemas.android.com/tools "})
etree.Element("manifest", nsmap={"tools": "http://schemas.android.com/tools "})
File src/lxml/etree.pyx:3022, in lxml.etree.Element()
File src/lxml/apihelpers.pxi:131, in lxml.etree._makeElement()
File src/lxml/apihelpers.pxi:118, in lxml.etree._makeElement()
File …
```
=> [bugfix] Remove spaces from nsmap

pyproject.toml
Fixes https://github.com/androguard/androguard/issues/1027 and https://github.com/androguard/androguard/issues/1018
=> address pyqt5-qt5 inconsistencies by adding markers for MacOS ARM targets 

androguard/cli/cli.py, androguard/cli/main.py, androguard/core/bytecode.py, tests/test_callgraph.py, tests/test_cli_decompile.py
* Fix https://github.com/androguard/androguard/issues/1033
* Create basic unit test for decompilation
=> Use get_encoded_methods() when decompiling

androguard/core/axml/__init__.py
Related with #953
**Changes**
Find a way to keep all information about AndroidManifest, I didnt find a file with issue mention in #953 there so if a sample is available it could be very nice, but normally it should not affect the number of information provided by the AndroidManifest.
Please don't merge it without review and test with the file issue. I let @danielgf3 answer about that.
=> Correct attribute name to be the same used by Android

androguard/core/axml/__init__.py
we keep tackling evasive malware :D
https://tria.ge/240418-h2h1haed74/static1
=> reject decoding strings that are passing the string block in size

androguard/core/axml/__init__.py
Namespace-altering applications detected.
[6a2f19dba563ca02b3a55edd74798e97db83bcc58cd77bef6a627af69facb401](https://www.virustotal.com/gui/file/6a2f19dba563ca02b3a55edd74798e97db83bcc58cd77bef6a627af69facb401/details)
```
nsmap= {'<!--': 'http://schemas.android.com/apk/res/android'}
```
```xml
<uses-permission
<!--:name="android.permission.INTERNET" />
<permission
<!--:name="com.example.test.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION"
<!--:protectionLevel="0x2" />
<uses-permission
<!--:name="com.example.test.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION" />
<application
<!--:theme="@ref/0x7f100272"
<!--:label="@ref/0x7f0f001c"
<!--:icon="@ref/0x7f0d0000"
<!--:allowBackup="true"
<!--:supportsRtl="true"
<!--:extractNativeLibs="false"
<!--:fullBackupContent="@ref/0x7f120000" …
```
=> Fix invalid nsmap

androguard/session.py
This allows specifying a custom database URL, which enables in-memory processing using `db_url='sqlite:///:memory:'`. Also could be useful for tests and running multiple androguard instances in parallel.
=> Allow a custom db_url in Session

androguard/decompiler/dast.py, androguard/decompiler/decompile.py
Converts functions in `androguard.decompiler.dast` into instance or static methods without changing their behaviour in any way. The modifications are supposed to be cosmetic and were carefully reviewed not to affect any existing functionality. Every change was introduced in a separate commit to make reviewing easier, but feel free to squash them.
With the previous version of the code it was difficult to alter the functionality of the `JSONWriter` class.
For some methods in `JSONWriter`, expanding the behaviour in a subclass would require re-implementing entire code blocks or using monkey patching.
Please take a look at the following example:
In the original version of the code the `androguard.decompiler.dast` module contains a function called `method_invocation`. It is used in another …
=> Convert `androguard.decompiler.dast` functions into instance or static methods

androguard/decompiler/graph.py
Possible fix for #1079. More details available in the issue and commit messages.
=> Fix empty `catch_type` in catch nodes

androguard/core/axml/__init__.py, tests/test_arsc.py
This PR fixes an issue in `get_res_id_by_key` where `self._analyse()` was missing. Without this call, `self.resource_keys` remains uninitialized, always resulting in a `KeyError`. The fix ensures that `_analyse()` is invoked before accessing `self.resource_keys`.  
- Added `self._analyse()` at the beginning of `get_res_id_by_key`.
- Added type annotations for `get_res_id_by_key`.
- Added a unit test for `get_res_id_by_key`.
=> fix: Ensure _analyse is called before accessing resource_keys object.
